export enum StatusResponseEnum {
    FAILED = 'FAILED',
    SUCCESS = 'SUCCESS'
}

export enum MessageResponseEnum {
    USERNAME_IS_REQUIRED = 'USERNAME IS REQUIRED',
    PASSWORD_IS_REQUIRED = 'PASSWORD IS REQUIRED',
    USERNAME_ALREADY_EXISTS = 'USERNAME ALREADY TAKEN',
    USER_CREATED_SUCCESSFULLY = 'USER CREATED SUCCESSFULLY',
    INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
    USER_DOES_NOT_EXISTS = 'USER DOES NOT EXISTS',
    INAVLID_CREDENTIALS = "INVALID CREDENTIALS",
    AUTHENTICATION_SUCCESSFUL = 'AUTHENTICATION SUCCESSFUL',
    NEW_PASSWORD_IS_REQUIRED = 'NEW PASSWORD IS REQUIRED',
    PASSWORD_CANNOT_BE_SAME= 'PASSWORD CAN NOT BE SAME',
    PASSWORD_NOT_UPDATED = 'PASSWORD NOT UPDATED',
    PASSWORD_UPDATED_SUCCESSFULLY = 'PASSWORD UPDATED SUCCESSFULLY'
}